### ISSUE TITLE
Add ability to search for block headers by proposer

### ISSUE THREAD

**Issue by urtho** [AlgoNode/indexer-api-cdb#9]
a search type endpoint `/v2/blocks`

filters:
-  proposer : include blocks with matching proposer
-  updates : include blocks with a hit in either partupdrmv or partupdabs array
-  expired: include blocks with hits in partupdrmv array
-  participation: equal to (proposer OR updates)
-  absent: include blocks with hits in partupdabs
-  standard parameters from `/v2/transactions` endpoint 
    - limit, next
    - min-round, max-round
    - before-time, after-time

all filters are joined with AND 

note:
* assume that users might just call this endpoint for bulk round headers in a time range - without participation filters
* return only header object per block - like the block lookup with  `header-only` flag
* use GIN Array Indexes for  partupdrmv and partupdabs arrays
* assume all arrays and proposers are base32 (not base64) encoded in the DB

bonus feature:
- allow proposer/update/expired/participation to be arrays

**Comment by urtho** [comment]
users reporting absent filter not working:
https://discord.com/channels/491256308461207573/1267759463734054922/1298952798020571146

**Comment by urtho** [comment]
Never mind the previous comment - some blocks are encoded incorrectly because we've been running the old conduit for a bit.

**Comment by urtho** [comment]
Swagger doc reuses block response example that include some transactions .
We should have a different example without transactions. 

https://nodely.io/swagger/index.html?url=/swagger/api/fnet/indexer.oas3.yml#/search/searchForBlocks

**Comment by agodnic** [comment]
> Swagger doc reuses block response example that include some transactions . We should have a different example without transactions.
> 
> https://nodely.io/swagger/index.html?url=/swagger/api/fnet/indexer.oas3.yml#/search/searchForBlocks

Addressed in https://github.com/AlgoNode/indexer-api-cdb/pull/11
